name: cartography
channels:
    - conda-forge
dependencies:
    - python>=3.6
    - cartopy
    - cython
    - descartes
    - fiona
    - jupyter
    - matplotlib
    - numpy
    - pandas
    - pyqt=5
    - requests
    - scipy
    - shapely
    - skyfield
    - zeep
    - pip:
        - geodesy
