name: cartography
channels:
    - conda-forge
dependencies:
    - python=3.6*
    - cartopy
    - cython
    - descartes
    - fiona
    - jupyter
    - matplotlib
    - numpy
    - pandas
    - pyqt=5
    - scipy
    - shapely
    - skyfield
    - zeep
    - pip:
        - geodesy
        - extra/pyModeS-1.2.0-py3-none-any.whl
        - extra/adsb_py-0.1-py3-none-any.whl
